# Site settings
title: Raúl Salinas-Monteagudo's blog
email: 
description: "A blog on different technical topics related to programming, security and Linux"
baseurl: ""
url: "https://rsalinas.github.io/"

# Build settings
markdown: kramdown
permalink: pretty

